#!/bin/bash
yum update -y
useradd -p $(openssl passwd -1 TheBigNest123) steve
mkdir /home/steve
chmod 700 /home/steve
chown steve:steve /home/steve
usermod -s /bin/bash steve
mkdir /home/steve/.ssh
chown steve:steve /home/steve/.ssh
usermod -aG steve
echo 'steve ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
